default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: windfarms_rails_development

test:
  <<: *default
  database: windfarms_rails_test

production:
  <<: *default
  database: windfarms_rails_production
  username: windfarms_rails
  password: <%= ENV["WINDFARMS_RAILS_DATABASE_PASSWORD"] %>
